## 2. numpy 함수
+ numerical python  
+ 과학계산을 위한 파이썬 데이터분석 패키지  
+ 다양한 연산 기능을 제공  

### 2.1 다차원 배열(ndarray)
python은 배열을 이용할 수 없습니다. 쓰는 것 같았다면, list를 본 것입니다.  
array와 list의 차이점은 array는 정적인 메모리라 크기를 변경하려면 삭제 후 재생성해야 합니다.  
list는 그럴 필요가 없습니다. 동적인 메모리라 크기가 자유롭게 변합니다. 
+ 배열은 같은 자료형의 데이터를 담는 자료구조<font color=green> 예를들어 2행3열 (2차원)<font>  
+ __rank__: 배열의 차원<font color=green> 2<font>                 
+ __shape__: 각 차원의 크기를 튜플로 표시한 것<font color=green> (2,3)<font>         
+ 배열의 타입은 ndarray

__1. numpy 설치 (jupyter notebook은 이미 되어 있음)__  
__2. numpy 불러오기__

In [4]:
import numpy as np

#### 3. numpy 배열 생성하기
np.array([리스트요소1, 리스트요소2, ...])  
np.arange(시작, 끝, 간격) 혹은 np.arrange(끝)

In [18]:
arr = np.array([1,2,3,4]) # [1 2 3 4] 출력
arg1 = np.arange(1,10,2)  # [1 3 5 7 9] 출력
arg2 = np.arange(10)      # 0부터 10개의 수 [0 1 2 3 4 5 6 7 8 9] 출력
print(arr)
print(arg1)
print(arg2)

[1 2 3 4]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


리스트는 0부터 시작한다는 것을 기억하자!

#### 4. numpy 행렬 생성하기 (배열을 행렬로 변환하기)
배열(array): 동일한 자료형, 여러 개의 자료  
행렬(matrix): array의 하위 자료형, 수학계산에 좀 더 편리

In [19]:
mat = arg2.reshape(2,5) # 2행 5열의 행렬로 변환
print(mat) # [[0 1 2 3 4] [5 6 7 8 9]] 출력 

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 5. numpy 행렬 연산하기

In [29]:
arg3 = np.arange(1,11).reshape(2,5)
print(arg3)
arg4 = np.arange(11,21).reshape(2,5)
print(arg4)
print(np.add(arg3,arg4))      # 행렬의 덧셈
print(np.subtract(arg3,arg4)) # 행렬의 뺄셈
print(np.multiply(arg3,arg4)) # 행렬의 곱셈

sq_mat = np.arange(1,5).reshape(2,2)
print(np.dot(sq_mat,sq_mat))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[12 14 16 18 20]
 [22 24 26 28 30]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[ 7 10]
 [15 22]]


#### 6. 기타 명령어 

In [32]:
print(np.amin(arg3)) # 행렬의 최소값
print(np.amin(arg3)) # 행렬의 최대값
print(arg3.dtype)    # 자료구조의 자료형
print(arg3.shape)    # 자료구조의 크기(행,열,차원)

1
1
int64
(2, 5)
